// src/parts/part-status.enum.ts

export enum PartStatus {
  AVAILABLE = 'AVAILABLE',
  PENDING_COLLECTION = 'PENDING_COLLECTION',
  CLAIMED = 'CLAIMED',
  COLLECTED = 'COLLECTED',
  UNAVAILABLE = 'UNAVAILABLE',
}
